#theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: PANDA Workshop
description: The Second International Workshop on Performance-Data Analytics and Data-Management

theme: jekyll-theme-slate
